nohup condor_run "lein trampoline run --discussion-forum --start \"http://scififantasyforum.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://updatebaba.com/discussion/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://bbshowcase.org/forums/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.graphene-theme.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://climbkalymnos.com/bbpress/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.revolution.co.uk/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.pylucid.org/de/forum/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.alwaysdata.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.theadminzone.com/forums/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://springrts.com/phpbb/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forums.mozillazine.org/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.classicshell.net/forum/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.maniaplanet.com/index.php\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://photography-on-the.net/forum/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://dgrin.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.doom9.org/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forum.vizrt.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://boards.straightdope.com/sdmb/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.absolutewrite.com/forums/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.qdma.com/forums/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forums.anandtech.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forums.iobit.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://boards.houstontexans.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://forums.eidosgames.com/\"" &
nohup condor_run "lein trampoline run --discussion-forum --start \"http://www.grimdawn.com/forums/\"" &
